default: &default
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: <%= ENV["DB_HOST"]%>
    username: <%=  ENV["DB_USERNAME"]%>
    password: <%=  ENV["DB_PASSWORD"]%>

development:
    <<: *default
    database: pairlydb

test:
    <<: *default
    database: pairlydb

production:
    <<: *default
    database: <%= ENV['DB_DATABASE'] %>
